// styles/global.ts
import { StyleSheet } from "react-native"

const GlobalStyles = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: "#0A0E27", // Deep navy blue for more fun dark mode
    padding: 16,
  },
  title: {
    color: "#FFD700", // Gold color for main title
    fontSize: 28,
    marginBottom: 16,
    fontWeight: "bold",
    textAlign: "center",
    textShadowColor: "rgba(255, 215, 0, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  h1: {
    color: "#FFD700",
    fontSize: 20,
    fontWeight: "bold",
    marginVertical: 10,
    textAlign: "center",
  },
  h2: {
    color: "#E0E0E0",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  button: {
    backgroundColor: "#00D9FF", // Cyan
    padding: 15,
    borderRadius: 25,
    marginVertical: 10,
    width: "80%",
    maxWidth: 300,
    alignItems: "center",
    alignSelf: "center",
    shadowColor: "#00D9FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  option: {
    padding: 12,
    borderWidth: 2,
    borderColor: "#4A5568",
    borderRadius: 15,
    marginHorizontal: 6,
    minWidth: 100,
    alignItems: "center",
    backgroundColor: "#1A1F3A",
  },
  selected: {
    backgroundColor: "#7C3AED", // Purple for selected state
    borderColor: "#A78BFA",
    shadowColor: "#7C3AED",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 3,
  },
  buttonSecondary: {
    backgroundColor: "#7C3AED", // Purple
    padding: 15,
    borderRadius: 25,
    marginVertical: 10,
    maxWidth: 300,
    alignItems: "center",
    alignSelf: "center",
    shadowColor: "#7C3AED",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonDanger: {
    backgroundColor: "#FF4757", // Brighter red
    padding: 15,
    borderRadius: 25,
    marginVertical: 10,
    width: "80%",
    maxWidth: 300,
    alignItems: "center",
    alignSelf: "center",
    shadowColor: "#FF4757",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  input: {
    color: "white",
    borderWidth: 2,
    borderColor: "#4A5568",
    backgroundColor: "#1A1F3A",
    padding: 12,
    borderRadius: 50, // Circular!
    marginVertical: 5,
    marginHorizontal: 4,
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    minWidth: 70,
  },
  row: {
    flexDirection: "row",
    marginVertical: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  cell: {
    borderWidth: 1,
    borderColor: "#2D3748",
    padding: 10,
    textAlign: "center",
    color: "#E0E0E0",
    flex: 1,
    fontSize: 14,
    backgroundColor: "#1A1F3A",
  },
  labelCell: {
    borderWidth: 1,
    borderColor: "#4A5568",
    padding: 10,
    textAlign: "center",
    backgroundColor: "#2D3748",
    color: "#FFD700",
    fontWeight: "bold",
    flex: 1,
    fontSize: 14,
  },
  teamCell: {
    borderWidth: 1,
    borderColor: "#4A5568",
    flex: 1,
    padding: 10,
    textAlign: "center",
    backgroundColor: "#2D3748",
    color: "#00D9FF",
    fontWeight: "bold",
    fontSize: 16,
  },
  highlightCell: {
    backgroundColor: "#2D3748",
  },
  errorText: {
    color: "#FF4757",
    fontSize: 16,
    marginVertical: 10,
    textAlign: "center",
    fontWeight: "600",
  },
  totalContainer: {
    paddingVertical: 12,
    marginVertical: 8,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  totalItem: {
    alignItems: "center",
    flex: 1,
  },
  totalLabel: {
    color: "#A0AEC0",
    fontSize: 14,
    marginBottom: 8,
    fontWeight: "600",
  },
  totalValue: {
    color: "#FFD700",
    fontSize: 32,
    fontWeight: "bold",
    textShadowColor: "rgba(255, 215, 0, 0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  inputSection: {
    paddingVertical: 8,
    marginVertical: 8,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
    justifyContent: "space-between",
  },
  teamLabel: {
    color: "#00D9FF",
    fontSize: 18,
    fontWeight: "bold",
    width: 80,
  },
  inputGroup: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "space-around",
  },
  actionButton: {
    padding: 8,
    borderRadius: 15,
    marginLeft: 6,
    minWidth: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  tableContainer: {
    paddingVertical: 8,
    marginVertical: 8,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderColor: "#4A5568",
    paddingBottom: 8,
    marginBottom: 8,
  },
  tableHeaderText: {
    color: "#FFD700",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 12,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#2D3748",
    paddingVertical: 8,
  },
  gaidRow: {
    backgroundColor: "#8B0000",
  },
  tableText: {
    color: "#E0E0E0",
    textAlign: "center",
    fontSize: 14,
  },
})

export default GlobalStyles
